/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AlarmPane: typeof import('./src/components/AlarmPane.vue')['default']
    ChartLines: typeof import('./src/components/ChartLines.vue')['default']
    ChartRadar: typeof import('./src/components/ChartRadar.vue')['default']
    ChartWave: typeof import('./src/components/ChartWave.vue')['default']
    Content: typeof import('./src/components/Content.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElBadge: typeof import('element-plus/es')['ElBadge']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElRadioButton: typeof import('element-plus/es')['ElRadioButton']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    IEpArrowDown: typeof import('~icons/ep/arrow-down')['default']
    IEpBellFilled: typeof import('~icons/ep/bell-filled')['default']
    IEpUserFilled: typeof import('~icons/ep/user-filled')['default']
    InfoPane: typeof import('./src/components/InfoPane.vue')['default']
    LHeader: typeof import('./src/components/LHeader.vue')['default']
    RightPane: typeof import('./src/components/RightPane.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    RunStatus: typeof import('./src/components/RunStatus.vue')['default']
    SideMenu: typeof import('./src/components/SideMenu.vue')['default']
    SvgIcon: typeof import('./src/components/SvgIcon.vue')['default']
    Title1: typeof import('./src/components/Title1.vue')['default']
  }
}
